2025-08-20T11:21:15.896520+00:00 heroku[router]: at=info method=POST path="/webhooks/sms" host=lead-qualifier-staging-4eff728d5bbf.herokuapp.com request_id=0068917a-10ae-371b-0574-a22d03205871 fwd="34.44.20.245" dyno=web.1 connect=0ms service=25ms status=500 bytes=21 protocol=http1.1 tls=true tls_version=unknown
2025-08-20T11:21:15.900282+00:00 app[web.1]: ERROR:    Exception in ASGI application
2025-08-20T11:21:15.900282+00:00 app[web.1]: Traceback (most recent call last):
2025-08-20T11:21:15.900283+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
2025-08-20T11:21:15.900283+00:00 app[web.1]: result = await app(  # type: ignore[func-returns-value]
2025-08-20T11:21:15.900283+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-20T11:21:15.900284+00:00 app[web.1]: self.scope, self.receive, self.send
2025-08-20T11:21:15.900284+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-20T11:21:15.900284+00:00 app[web.1]: )
2025-08-20T11:21:15.900285+00:00 app[web.1]: ^
2025-08-20T11:21:15.900285+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
2025-08-20T11:21:15.900285+00:00 app[web.1]: return await self.app(scope, receive, send)
2025-08-20T11:21:15.900285+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-20T11:21:15.900286+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
2025-08-20T11:21:15.900286+00:00 app[web.1]: await super().__call__(scope, receive, send)
2025-08-20T11:21:15.900286+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
2025-08-20T11:21:15.900286+00:00 app[web.1]: await self.middleware_stack(scope, receive, send)
2025-08-20T11:21:15.900286+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
2025-08-20T11:21:15.900287+00:00 app[web.1]: raise exc
2025-08-20T11:21:15.900287+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
2025-08-20T11:21:15.900287+00:00 app[web.1]: await self.app(scope, receive, _send)
2025-08-20T11:21:15.900287+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
2025-08-20T11:21:15.900288+00:00 app[web.1]: await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2025-08-20T11:21:15.900288+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-08-20T11:21:15.900288+00:00 app[web.1]: raise exc
2025-08-20T11:21:15.900288+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-08-20T11:21:15.900289+00:00 app[web.1]: await app(scope, receive, sender)
2025-08-20T11:21:15.900289+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
2025-08-20T11:21:15.900289+00:00 app[web.1]: await self.middleware_stack(scope, receive, send)
2025-08-20T11:21:15.900289+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
2025-08-20T11:21:15.900289+00:00 app[web.1]: await route.handle(scope, receive, send)
2025-08-20T11:21:15.900289+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
2025-08-20T11:21:15.900289+00:00 app[web.1]: await self.app(scope, receive, send)
2025-08-20T11:21:15.900290+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
2025-08-20T11:21:15.900290+00:00 app[web.1]: await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2025-08-20T11:21:15.900290+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2025-08-20T11:21:15.900290+00:00 app[web.1]: raise exc
2025-08-20T11:21:15.900290+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
2025-08-20T11:21:15.900290+00:00 app[web.1]: await app(scope, receive, sender)
2025-08-20T11:21:15.900290+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
2025-08-20T11:21:15.900291+00:00 app[web.1]: response = await f(request)
2025-08-20T11:21:15.900291+00:00 app[web.1]: ^^^^^^^^^^^^^^^^
2025-08-20T11:21:15.900291+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
2025-08-20T11:21:15.900291+00:00 app[web.1]: raw_response = await run_endpoint_function(
2025-08-20T11:21:15.900292+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-20T11:21:15.900292+00:00 app[web.1]: ...<3 lines>...
2025-08-20T11:21:15.900292+00:00 app[web.1]: )
2025-08-20T11:21:15.900292+00:00 app[web.1]: ^
2025-08-20T11:21:15.900292+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
2025-08-20T11:21:15.900293+00:00 app[web.1]: return await dependant.call(**values)
2025-08-20T11:21:15.900293+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-20T11:21:15.900293+00:00 app[web.1]: File "/app/api/webhooks.py", line 35, in sms_webhook
2025-08-20T11:21:15.900293+00:00 app[web.1]: handler = MessageWebhookHandler(session)
2025-08-20T11:21:15.900293+00:00 app[web.1]: File "/app/modules/messaging/webhook_handler.py", line 39, in __init__
2025-08-20T11:21:15.900293+00:00 app[web.1]: self.qualification_service = QualificationService(session, openai_client)
2025-08-20T11:21:15.900294+00:00 app[web.1]: ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-20T11:21:15.900294+00:00 app[web.1]: TypeError: QualificationService.__init__() takes 1 positional argument but 3 were given